[project]
name = "PlotNeuralNetPy"
dynamic = ["version"]
dependencies = []
authors = [
    {name = "HarisIqbal88", email = "???@???.com"},
]
readme = "README.md"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[tool.setuptools.dynamic]
version = {attr = "PlotNeuralNetPy.version.__version__"}